In [2]:
import numpy as np
from pprint import pprint

In [6]:
# EX01 - CORRECT
# Suppose the people who own page 3 in the web of Figure 1 are infuriated by the fact that its 
# importance score, computed using formula (2.1), is lower than the score of page 1. In an attempt to 
# boost page 3’s score, they create a page 5 that links to page 3; page 3 also links to page 5. 
# Does this boost page 3’s score above that of page 1?

A = np.array([[0, 0, 0.5, 0.5, 0], 
              [1/3, 0, 0, 0, 0], 
              [1/3, 1/2, 0, 1/2, 1], 
              [1/3, 1/2, 0, 0, 0], 
              [0, 0, 0.5, 0, 0]])

eigenvalues, eigenvectors = np.linalg.eig(A)
tol = 1e-7 
mask = np.abs(eigenvalues-1) < tol
print(f"\nMask for eigenvalues close to 1: {mask}")
eigenspace_basis = eigenvectors[:, mask]
# print(f"\nEigenspace basis for eigenvalue 1:")
# print(eigenspace_basis)
print("Normalized")
print(eigenspace_basis)
normalized = eigenspace_basis/np.sum(eigenspace_basis)
print(normalized)
print(f"First ranked page is {np.argmax(normalized)+1}")
print(f"The dimension o V1(A) is {eigenspace_basis.shape}")


Mask for eigenvalues close to 1: [ True False False False False]
Normalized
[[-0.48949021+0.j]
 [-0.1631634 +0.j]
 [-0.73423531+0.j]
 [-0.2447451 +0.j]
 [-0.36711766+0.j]]
[[0.24489796-0.j]
 [0.08163265-0.j]
 [0.36734694-0.j]
 [0.12244898-0.j]
 [0.18367347-0.j]]
First ranked page is 3
The dimension o V1(A) is (5, 1)


In [5]:
# EX02 - CORRECT
# Construct a web consisting of three or more subwebs and verify that dim(V1(A)) equals (or exceeds) 
# the number of the components in the web.

web = np.array([[0, 1, 0, 0, 0, 0, 0], 
              [1, 0, 0, 0, 0, 0, 0], 
              [0, 0, 0, 1/2, 1, 0, 0], 
              [0, 0, 1/2, 0, 0, 0, 0], 
              [0, 0, 1/2, 1/2, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 1],
              [0, 0, 0, 0, 0, 1, 0]])
print(web)
eigenvalues, eigenvectors = np.linalg.eig(web)
tol = 1e-7 
mask = np.abs(eigenvalues-1) < tol
eigenspace_basis = eigenvectors[:, mask]
print(f"The dimension of V1(A) is {eigenspace_basis.shape}, which is >= ({web.shape[0]}, 1)")


[[0.  1.  0.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 1.  0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0. ]
 [0.  0.  0.5 0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1. ]
 [0.  0.  0.  0.  0.  1.  0. ]]
The dimension of V1(A) is (7, 3), which is >= (7, 1)


In [6]:
# EX03 - Does V1(A) have to have dimension 1 as the graph is connected?
# Add a link from page 5 to page 1 in the web of Figure 2. The resulting web, considered as an 
# undirected graph, is connected. What is the dimension of V1(A)?

A = np.array([[0, 1, 0, 0, 1/3], 
              [1, 0, 0, 0, 0], 
              [0, 0, 0, 1, 1/3], 
              [0, 0, 1, 0, 1/3], 
              [0, 0, 0, 0, 0]])
eigenvalues, eigenvectors = np.linalg.eig(A)
tol = 1e-7 
mask = np.abs(eigenvalues-1) < tol
eigenspace_basis = eigenvectors[:, mask]
print(f"The dimension o V1(A) is {eigenspace_basis.shape}")

The dimension o V1(A) is (5, 2)


In [7]:
# EX04 - CORRECT
# In the web of Figure 2.1, remove the link from page 3 to page 1. In the resulting web page 3 is now 
# a dangling node. Set up the corresponding substochastic matrix and find its largest positive 
# (Perron) eigenvalue. Find a non-negative Perron eigenvector for this eigenvalue, and scale the 
# vector so that components sum to one. Does the resulting ranking seem reasonable?

A = np.array([[0, 0, 0, 0.5], 
              [1/3, 0, 0, 0], 
              [1/3, 1/2, 0, 1/2], 
              [1/3, 1/2, 0, 0]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
tol = 1e-7 
max = np.argmax(eigenvalues)
eigenspace_basis = eigenvectors[:, max]
normalized = eigenspace_basis/np.sum(eigenspace_basis)
print(normalized)
print(f"Rank = {np.real(normalized)} seems reasonable.")
# In fact The corresponding substochastic matrix must have a positive eigenvalue λ ≤ 1 and a 
# corresponding eigenvector x with non-negative entries (called the Perron eigenvector) that can be 
# used to rank the web pages")

[ 0.        +0.j         -0.28067662+0.26395346j -0.28067662-0.26395346j
  0.56135324+0.j        ]
[0.20664504-0.j 0.12270648-0.j 0.43864676-0.j 0.23200172-0.j]
Rank = [0.20664504 0.12270648 0.43864676 0.23200172] seems reasonable.


In [10]:
print(normalized)

[0.20664504-0.j 0.12270648-0.j 0.43864676-0.j 0.23200172-0.j]


In [6]:
# EX05 - CORRECT
# Prove that in any web the importance score of a page with no backlinks is zero

# As the matrix is column-stochastic, every eigenvalue is non-negative and there is i for which λ(i) = 1
# As Ax = λx and the j-th row of A is 0 (in fact j is the page with no backlinks), we know that the j-th 
# element of Ax will be 0. So (λx)[j] = 0, and since λ = 1, x[j] = 0

# Just an example
n = 5
A = np.random.random((n, n))*(np.ones((n,n), dtype=float)-np.eye(n))
ind = 3
print(f"Page {ind+1} has no backlinks")
A[ind, :] = 0
A = A/np.sum(A, axis = 0)
eigenvalues, eigenvectors = np.linalg.eig(A)
tol = 1e-7 
mask = np.abs(eigenvalues-1) < tol
eigenspace_basis = eigenvectors[:, mask]
print(f"λ = {np.real(eigenvalues[mask])} and its corresponding eigenvector is\n {np.real(eigenspace_basis).T}")
print(f"with λ = 1 -> Ax = λx = \n ={np.real(A@eigenspace_basis).T}")
print(f"Important score of page {ind+1} -> {np.real(eigenspace_basis[ind])}")

Page 4 has no backlinks
λ = [1.] and its corresponding eigenvector is
 [[-0.55088069 -0.48344495 -0.5400928   0.         -0.41365592]]
with λ = 1 -> Ax = λx = 
 =[[-0.55088069 -0.48344495 -0.5400928   0.         -0.41365592]]
Important score of page 4 -> [0.]


In [7]:
# EX06 - TODO

A = np.array([[0, 0, 0.5, 0.5, 0], 
              [1/3, 0, 0, 0, 0], 
              [1/3, 1/2, 0, 1/2, 1], 
              [1/3, 1/2, 0, 0, 0], 
              [0, 0, 0.5, 0, 0]])
n = A.shape[0]
# two indeces to swap
i = 0
j = 2
P = np.eye(n)
P[[i, j]] = P[[j, i]]
A_tilde = P@A@P
A_eigenvalues, A_eigenvectors = np.linalg.eig(A)
k = np.random.randint(0, n)
x = A_eigenvectors[k]
A_tilde_eigenvalues, A_tilde_eigenvectors = np.linalg.eig(A_tilde)
y = P@x
tol = 1e-7
lam = A_eigenvalues[k]
# Verify A_tilde y ≈ lam * y
residual = np.linalg.norm(A_tilde @ y - lam * y)
print("chosen index k =", k)
print("λ =", lam)
print("norm(A_tilde @ y - λ*y) =", residual)
if residual < tol:
    print("Success: y = P x is an eigenvector of A_tilde (within tolerance).")
else:
    print("Not within tolerance. Residual:", residual)

chosen index k = 1
λ = (0.33633115969816535+0j)
norm(A_tilde @ y - λ*y) = 0.6316608984899779
Not within tolerance. Residual: 0.6316608984899779


In [8]:
# EX07 - CORRECT
# Prove that if A is an n × n column-stochastic matrix and 0 ≤ m ≤ 1, then M = (1 − m)A + mS is also a
# column-stochastic matrix

import random
n = 4
A = np.random.random((n,  n))*(np.ones((n,n), dtype=float)-np.eye(n))
A = A/np.sum(A, axis=0)
print("A is column-stochastic by construction ->", np.sum(A, axis = 0))
m = random.random()
print(f"m = {m} is a random value")
print("(1-m)*A is not column-stochastic ->\n", np.sum((1-m)*A, axis = 0))
print("In fact, every column sums to (1-m)")
S = np.zeros((n, n), dtype=float)
S[:,:] = 1/n
print("S is column-stochastic (S columns sum to 1 as they are n * 1/n) ->\n", np.sum(S, axis = 0))
print("As a consequence, we'll have for each column (1-m)*sum(columns of A) + m*(sum of columns of S) = " \
"(1-m)*1 + m*1 = 1")
M = (1-m)*A + m*S
sum = np.sum(M, axis = 0)
print("M is column-stochastic ->", sum)

A is column-stochastic by construction -> [1. 1. 1. 1.]
m = 0.9064502303980368 is a random value
(1-m)*A is not column-stochastic ->
 [0.09354977 0.09354977 0.09354977 0.09354977]
In fact, every column sums to (1-m)
S is column-stochastic (S columns sum to 1 as they are n * 1/n) ->
 [1. 1. 1. 1.]
As a consequence, we'll have for each column (1-m)*sum(columns of A) + m*(sum of columns of S) = (1-m)*1 + m*1 = 1
M is column-stochastic -> [1. 1. 1. 1.]


In [9]:
# EX08 - I have to demonstrate it
# Show that the product of two column-stochastic matrices is also column-stochastic

# Just an example
n = 4
A = np.random.random((n,  n))*(np.ones((n,n), dtype=float)-np.eye(n))
A = A/np.sum(A, axis=0)
m = random.random()
S = np.zeros((n, n), dtype=float)
S[:,:] = 1/n
M = (1-m)*A + m*S
print("Taken two random columns-stochastic matrix (A and M) its product will be:")
ris = A@M
print(ris)
print("which is columns stochastic, as its columns sum to 1 ->", np.sum(ris, axis=0))

Taken two random columns-stochastic matrix (A and M) its product will be:
[[0.28482501 0.17387285 0.24719725 0.3029123 ]
 [0.23909461 0.28133623 0.20032597 0.24552505]
 [0.32243199 0.28480456 0.41029625 0.23468963]
 [0.15364839 0.25998636 0.14218053 0.21687301]]
which is columns stochastic, as its columns sum to 1 -> [1. 1. 1. 1.]


In [ ]:
# EX09 - CORRECT
# Show that a page with no backlinks is given importance score m/n by x = (1 − m)Ax + mS

n = 6
A = np.random.random((n,  n))*(np.ones((n,n), dtype=float)-np.eye(n))
i = 2 # page 3 has no backlinks
print(f"Page {i+1} has no backlinks")
A[i, :] = 0
A = A/np.sum(A, axis = 0)
m = random.random()
S = np.zeros((n, n), dtype=float)
S[:,:] = 1/n
M = (1-m)*A + m*S
eigenvalues, eigenvectors = np.linalg.eig(M)
tol = 1e-7 
mask = np.abs(eigenvalues-1) < tol
eigenspace_basis = eigenvectors[:, mask]
print(eigenspace_basis)
normalized = eigenspace_basis/np.sum(eigenspace_basis)
print(f"Importance of page {i+1} is {np.real(normalized[i])}, which is equal to m/n = {m/n}")


Page 3 has no backlinks
[[-0.48412833+0.j]
 [-0.53112384+0.j]
 [-0.14025593+0.j]
 [-0.40361851+0.j]
 [-0.37514991+0.j]
 [-0.4002626 +0.j]]
Importance of page 3 is [0.06007864], which is equal to m/n = 0.06007863817232023


In [11]:
# 10
# Suppose that A is the link matrix for a strongly connected web of n pages (any page can be reached from any other 
# page by following a finite number of links). Show that dim(V1(A)) = 1

A = np.array([[0, 1, 0., 0., 0.],
       [0., 0., 1, 0., 0.],
       [0., 0., 0., 1, 0.],
       [0., 0., 0., 0, 1],
       [1, 0., 0., 0., 0.]])
n = A.shape[0]
# print(A)
print("Page 2 can be reached from page 1 by following 1 link")
print("Page 3 can be reached from page 1 by following 2 link")
print("Page 4 can be reached from page 1 by following 3 link")
print("Page 5 can be reached from page 1 by following 4 link")
A = A/np.sum(A, axis = 0)

# Let (A^k)ij denote the (i, j)-entry of A^k
# show that (A2)ij > 0 if and only if page i can be reached from page j in exactly two step
tmp = A
print()
print("-" * 20, "Let's verify", "-" * 20)
for i in range(2, 5):
    tmp = tmp@A
    print(f"A^{i}(page1, page{i+1}) should be larger than 0 -> {tmp[0, i]}")
    if i != 4:
        print(f"A^{i}(page1, page{i+2}) should be equal to 0 -> {tmp[0, i+1]}")
    print("-" * 50)

# Let (A^k)ij denote the (i, j)-entry of A^k



Page 2 can be reached from page 1 by following 1 link
Page 3 can be reached from page 1 by following 2 link
Page 4 can be reached from page 1 by following 3 link
Page 5 can be reached from page 1 by following 4 link

-------------------- Let's verify --------------------
A^2(page1, page3) should be larger than 0 -> 1.0
A^2(page1, page4) should be equal to 0 -> 0.0
--------------------------------------------------
A^3(page1, page4) should be larger than 0 -> 1.0
A^3(page1, page5) should be equal to 0 -> 0.0
--------------------------------------------------
A^4(page1, page5) should be larger than 0 -> 1.0
--------------------------------------------------


In [12]:
# EX11 - CORRECT
# Consider again the web in Figure 2.1, with the addition of a page 5 that links to page 3, where page 
# 3 also links to page 5. Calculate the new ranking by finding the eigenvector of M (corresponding to 
# λ = 1) that has positive components summing to one. Use m = 0.15

A = np.array([[0, 0, 0.5, 0.5, 0], 
              [1/3, 0, 0, 0, 0], 
              [1/3, 1/2, 0, 1/2, 1], 
              [1/3, 1/2, 0, 0, 0], 
              [0, 0, 0.5, 0, 0]])
n = A.shape[0]
S = np.zeros((n, n), dtype=float)
S[:,:] = 1/n
m = 0.15
M = (1-m)*A + m*S
eigenvalues, eigenvectors = np.linalg.eig(M)
tol = 1e-7 
mask = np.abs(eigenvalues-1) < tol
eigenspace_basis = eigenvectors[:, mask]
normalized = eigenspace_basis/np.sum(eigenspace_basis)
print(f"Ranking is {np.real(normalized.T)}")
print(f"First ranked page is {np.argmax(normalized)+1}")

Ranking is [[0.23714058 0.09718983 0.34889409 0.13849551 0.17827999]]
First ranked page is 3


In [13]:
# EX12 - CORRECT
# Add a sixth page that links to every page of the web in the previous exercise, but to which no other 
# page links. Rank the pages using A, then using M with m = 0.15, and compare the results.

A = np.array([[0, 0, 0.5, 0.5, 0, 1/5], 
              [1/3, 0, 0, 0, 0, 1/5], 
              [1/3, 1/2, 0, 1/2, 1, 1/5], 
              [1/3, 1/2, 0, 0, 0, 1/5], 
              [0, 0, 0.5, 0, 0, 1/5],
              [0, 0, 0, 0, 0, 0]])

# Rank using A
eigenvalues, eigenvectors = np.linalg.eig(A)
tol = 1e-7 
mask = np.abs(eigenvalues-1) < tol
eigenspace_basis = eigenvectors[:, mask]
normalized = eigenspace_basis/np.sum(eigenspace_basis)
print(f"Ranking using A is {np.real(normalized.T)}")
print(f"First ranked page with M is {np.argmax(normalized)+1}")

# Rank using M
n = A.shape[0]
S = np.zeros((n, n), dtype=float)
S[:,:] = 1/n
m = 0.15
M = (1-m)*A + m*S
eigenvalues, eigenvectors = np.linalg.eig(M)
mask = np.abs(eigenvalues-1) < tol
eigenspace_basis = eigenvectors[:, mask]
normalized = eigenspace_basis/np.sum(eigenspace_basis)
print(f"Ranking using M is {np.real(normalized.T)}")
print(f"First ranked page with M is {np.argmax(normalized)+1}")

Ranking using A is [[ 0.24489796  0.08163265  0.36734694  0.12244898  0.18367347 -0.        ]]
First ranked page with M is 3
Ranking using M is [[0.23121207 0.09476009 0.34017174 0.13503312 0.17382299 0.025     ]]
First ranked page with M is 3


In [14]:
# EX13 - CORRECT
# Construct a web consisting of two or more subwebs and determine the ranking given by 
# M = (1 − m)A + mS

A = np.array([[0, 1, 0, 0, 0, 0, 0], 
              [1, 0, 0, 0, 0, 0, 0], 
              [0, 0, 0, 1/2, 1, 0, 0], 
              [0, 0, 1/2, 0, 0, 0, 0], 
              [0, 0, 1/2, 1/2, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 1],
              [0, 0, 0, 0, 0, 1, 0]])
print(A)
n = A.shape[0]
S = np.zeros((n, n), dtype=float)
S[:,:] = 1/n
m = 0.15
M = (1-m)*A + m*S
eigenvalues, eigenvectors = np.linalg.eig(M)
tol = 1e-7
mask = np.abs(eigenvalues-1) < tol
eigenspace_basis = eigenvectors[:, mask]
normalized = eigenspace_basis/np.sum(eigenspace_basis)
print(f"Ranking is {np.real(normalized.T)}")
print(f"First ranked page is {np.argmax(normalized)+1}")

[[0.  1.  0.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 1.  0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0. ]
 [0.  0.  0.5 0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1. ]
 [0.  0.  0.  0.  0.  1.  0. ]]
Ranking is [[0.14285714 0.14285714 0.18546366 0.10025063 0.14285714 0.14285714
  0.14285714]]
First ranked page is 3


In [23]:
# EX14
# For the web in Exercise 11, compute the values of ‖Mkx0 −q‖1 and ‖Mk x0−q‖1/‖Mk−1x0−q‖1 for k = 1, 5, 10, 50, using 
# an initial guess x0 not too close to the actual eigenvector q (so that you can watch the convergence). Determine 
# c = max1≤j≤n |1 − 2 min1≤i≤n Mij | and the absolute value of the second largest eigenvalue of M.

A = np.array([[0, 0, 0.5, 0.5, 0], 
              [1/3, 0, 0, 0, 0], 
              [1/3, 1/2, 0, 1/2, 1], 
              [1/3, 1/2, 0, 0, 0], 
              [0, 0, 0.5, 0, 0]])
n = A.shape[0]
S = np.zeros((n, n), dtype=float)
S[:,:] = 1/n
m = 0.15
M = (1-m)*A + m*S
eigenvalues, eigenvectors = np.linalg.eig(M)
tol = 1e-7
mask = np.abs(eigenvalues-1) < tol
eigenspace_basis = eigenvectors[:, mask]
q = eigenspace_basis/np.sum(eigenspace_basis)

x0 = np.random.random((n, 1))
x0 = x0/np.sum(x0) # normalize x0

for k in [1, 5, 10, 50]:
    Mk = M
    for i in range(1, k):
        Mk = Mk @ M
    prec = Mk @ x0 - q
    ris = Mk @ M @ x0 - q
    norm_k = np.linalg.norm(ris, ord=1)
    norm_k_minus_1 = np.linalg.norm(prec, ord=1)
    result = norm_k/norm_k_minus_1
    print(f"Iteration {k} -> norm(M^k*x0-q): {norm_k} (ratio k/k-1 -> {norm_k/norm_k_minus_1}")


Iteration 1 -> norm(M^k*x0-q): 0.3101008276992428 (ratio k/k-1 -> 0.6814268992289964
Iteration 5 -> norm(M^k*x0-q): 0.03897357157387153 (ratio k/k-1 -> 0.6015530270364844
Iteration 10 -> norm(M^k*x0-q): 0.00335674469246984 (ratio k/k-1 -> 0.6115380240036861
Iteration 50 -> norm(M^k*x0-q): 9.436049164257554e-12 (ratio k/k-1 -> 0.6112855229207685


In [16]:
# EX15

# M
n = 4
A = np.random.random((n,  n))*(np.ones((n,n), dtype=float)-np.eye(n))
S = np.zeros((n, n), dtype=float)
S[:,:] = 1/n
m = 0.15
M = (1-m)*A + m*S
if np.linalg.matrix_rank(M) == n:
    print("M is diagonalizable")

# x0
x0 = np.random.random((n, 1))
x0 = x0/np.sum(x0)

# 
k = n - 1
Mk = np.copy(M)
for i in range(1, k):
    Mk = Mk@M
matrix = Mk@x0

M is diagonalizable


In [17]:
# EX16
# Show that M = (1 − m)A + mS (all Sij = 1/3) is not diagonalizable for 0 ≤ m < 1

A = np.array([[0, 0.5, 0.5],
              [0, 0, 0.5],
              [1, 0.5, 0]])
S = np.ones(A.shape)/A.shape[0]
m = 0.15 # just a try
M = (1-m)*A + m*S
if np.linalg.matrix_rank(M) == n:
    print("M is diagonalizable")
else:
    print("M is NOT diagonalizable")

M is NOT diagonalizable
